const CHECKPOINTS = {
  HOME_DEPARTURE: 'HOME_DEPARTURE',
  SCHOOL_ARRIVAL: 'SCHOOL_ARRIVAL',
  SCHOOL_DEPARTURE: 'SCHOOL_DEPARTURE',
  HOME_ARRIVAL: 'HOME_ARRIVAL',
};

const CHECKPOINT_ORDER = [
  CHECKPOINTS.HOME_DEPARTURE,
  CHECKPOINTS.SCHOOL_ARRIVAL,
  CHECKPOINTS.SCHOOL_DEPARTURE,
  CHECKPOINTS.HOME_ARRIVAL,
];

const CHECKPOINT_CONFIRMERS = {
  [CHECKPOINTS.HOME_DEPARTURE]: ['parent'],
  [CHECKPOINTS.SCHOOL_ARRIVAL]: ['student'],
  [CHECKPOINTS.SCHOOL_DEPARTURE]: ['teacher', 'student'],
  [CHECKPOINTS.HOME_ARRIVAL]: ['parent'],
};

const ALERT_STATUS = {
  NONE: 'NONE',
  LEVEL_1: 'LEVEL_1',
  LEVEL_2: 'LEVEL_2',
  LEVEL_3: 'LEVEL_3',
};

const JOURNEY_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ALERT_ACTIVE: 'ALERT_ACTIVE',
  EMERGENCY: 'EMERGENCY',
};

const ROLES = {
  PARENT: 'parent',
  STUDENT: 'student',
  TEACHER: 'teacher',
  ADMIN: 'admin',
  SECURITY: 'security',
};

const CHAT_MESSAGE_TYPES = {
  USER: 'user',
  SYSTEM: 'system',
  ALERT: 'alert',
  EMERGENCY: 'emergency',
};

module.exports = {
  CHECKPOINTS,
  CHECKPOINT_ORDER,
  CHECKPOINT_CONFIRMERS,
  ALERT_STATUS,
  JOURNEY_STATUS,
  ROLES,
  CHAT_MESSAGE_TYPES,
};